# Generated by Django 4.1.2 on 2023-02-07 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_quiz_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='category',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='image',
        ),
    ]
